services:
    sonata.admin.pn.page.page:
        class: ProjetNormandie\PageBundle\Admin\PageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "group.pages", label: "label.page" }
        arguments:
            - ~
            - ProjetNormandie\PageBundle\Entity\Page
            - ~
