services:
    sonata.admin.page.page:
        class: ProjetNormandie\PageBundle\Admin\PageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Pages", label: "Page" }
        arguments:
            - ~
            - ProjetNormandie\PageBundle\Entity\Page
            - ~
