resources:
    ProjetNormandie\PageBundle\Entity\Page:
        collectionOperations:
            get:
                normalization_context: {'groups': [page.list]}
                filters : ['article.filters']
        itemOperations:
            get:
                normalization_context: {'groups': [page.read]}
